# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# INSTALL PLUGIN RELLOAD
unless Vagrant.has_plugin?("vagrant-reload")
  puts 'Installing vagrant-reload Plugin...'
  system('vagrant plugin install vagrant-reload')
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "debian/bullseye64"

  # VM debian server
  config.vm.define "debian_ansible"  do |debian_ansible|

    # VARIABLE HOSTNAME
    APP_NAME= "debian-ansible"

    # HOSTNAME
    debian_ansible.vm.hostname = APP_NAME

    # NETWORK
    debian_ansible.vm.network "public_network" ,ip: "192.168.0.134",mode: "bridge" ,bridge: [
    "ens32",
    "Marvell AQtion 5Gbit Network Adapter"
    ]
    debian_ansible.vm.network "private_network" ,ip: "192.168.79.134"

    # MOUNTS
    debian_ansible.vm.synced_folder ".", "/vagrant", disabled: true
    debian_ansible.vm.synced_folder "./security", "/home/vagrant/security"
    debian_ansible.vm.synced_folder "./configs", "/home/vagrant/configs"

    # PROVIDER
    debian_ansible.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
      vb.name = APP_NAME
      vb.memory = 2048
      vb.cpus = 2
    end

    # PROVISION
    debian_ansible.vm.provision "shell", path: "scripts/install.sh"

  end

end
