---

# Install Commom Packages
- name: Install Packages
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - "{{ common_packages }}"

# Install nginx
- name: Install Web Server
  package:
    name: nginx
    state: latest

...

