---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: awx-dev
  name: awx-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - hosts:
    - debian-ansible-awx
  rules:
    - host: awx-dev.tesp2.local
      http:
        paths:
          - backend:
              service:
                name: awx-service
                port:
                  number: 80
            path: /
            pathType: Prefix


...
