---

# Update Debian
- name: Update System RPM (Debian, Ubuntu)
  apt:
    update_cache: yes
    upgrade: yes
  when: ansible_facts['os_family'] == "Debian"
  become: yes

# Update RPM
- name: Update System RPM (RedHat, OracleLinux,CentOS,Fedora)
  yum:
    name: '*'
    state: latest
    security: yes
  when: ansible_facts['os_family'] == "RedHat"
  become: yes

#Update Windows
- name: Update System Windows (Windows)
  win_updates:
    category_names:
      - SecurityUpdates
  when: ansible_facts['os_family'] == "Windows"

...

# https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html

# OS_FAMILY = dict(
#             RedHat = 'RedHat',
#             Fedora = 'RedHat',
#             CentOS = 'RedHat',
#             Scientific = 'RedHat',
#             SLC = 'RedHat',
#             Ascendos = 'RedHat',
#             CloudLinux = 'RedHat',
#             PSBM = 'RedHat',
#             OracleLinux = 'RedHat',
#             OVS = 'RedHat',
#             OEL = 'RedHat',
#             Amazon = 'RedHat',
#             XenServer = 'RedHat',
#             Ubuntu = 'Debian',
#             Debian = 'Debian',
#             SLES = 'Suse',
#             SLED = 'Suse',
#             OpenSuSE = 'Suse',
#             SuSE = 'Suse',
#             Gentoo = 'Gentoo',
#             Archlinux = 'Archlinux',
#             Mandriva = 'Mandrake',
#             Mandrake = 'Mandrake',
#             Solaris = 'Solaris',
#             Nexenta = 'Solaris',
#             OmniOS = 'Solaris',
#             OpenIndiana = 'Solaris',
#             SmartOS = 'Solaris',
#             AIX = 'AIX',
#             Alpine = 'Alpine',
#             MacOSX = 'Darwin',
#             FreeBSD = 'FreeBSD',
#             HPUX = 'HP-UX'
#         )